### ISSUE TITLE
Rooms just auto clear 

### ISSUE THREAD

**Issue by amoore2600** [gaz68/Arcade-TazzMania_MiSTer#1]
I have built the rom and the checksum match but something is wrong, the rooms just instantly auto clear with the exception of the bonus rooms. See youtube video: https://youtu.be/EDERLM3goVw

**Comment by gaz68** [comment]
I found this in the MAME source code:
  - When "Cabinet" is set to "Upright", press any player 2 joystick direction to end current level
    (code at 0x38dd). This trick does NOT work in bonus rooms though.

Joystick 1 and Joystick 2 are currently wired together hence the problem. I will fix this.

**Comment by gaz68** [comment]
Fix released. Player 2 Joystick is now disabled in Cabinet mode. Player 1 joystick is used for both players in Cabinet mode. Please download and use the new binary.

**Comment by NML32** [comment]
Thank you. Confirmed fixed with Arcade-TazzMania_20191006.rbf

**Comment by amoore2600** [comment]
Awesome work gaz68.

**Comment by amoore2600** [comment]
Awesome work gaz68.
